name: Build modrepo.xml and push to modrepo branch
description: Generates modrepo.xml in repo root and commits it to modrepo branch.

inputs:
  commit-message:
    required: false
    default: "Update modrepo.xml"

runs:
  using: composite
  steps:
    - name: Checkout caller repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Ensure xmllint is available
      shell: bash
      run: |
        if ! command -v xmllint >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
        fi
    - name: Build modrepo.xml
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # create/update local branch from remote if it exists
        git remote update
        git checkout -B modrepo origin/modrepo || { git checkout --orphan -b modrepo && git rm -rf .; }

        python3 "${{ github.action_path }}/build_modrepo.py"
        xmllint --noout modrepo.xml
        xmllint --pretty 2 modrepo.xml > modrepo.xml.tmp && mv modrepo.xml.tmp modrepo.xml

    - name: Publish modrepo.xml to target branch
      shell: bash
      run: |
        set -euo pipefail

        git add modrepo.xml modrepo_cache.json

        # no-op if unchanged
        if git diff --cached --quiet; then
          echo "modrepo.xml unchanged; nothing to commit."
          exit 0
        fi

        git commit -m "${{ inputs.commit-message }}"
        git push origin -f modrepo
